name: Prepare Release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  prepare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Update version and CHANGELOG
        id: update_files
        run: |
          cd frontend

          BUMP=$(npx -y \
            -p conventional-recommended-bump@9 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-recommended-bump -p conventionalcommits)

          if [ -z "$BUMP" ]; then BUMP=patch; fi

          npm version "$BUMP" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # 기존 CHANGELOG 내용을 임시 파일에 백업
          if [ -f CHANGELOG.md ]; then
            mv CHANGELOG.md OLD_CHANGELOG.md
          fi

          # 새로운 CHANGELOG 생성 (최신 내역만)
          npx -y \
            -p conventional-changelog-cli@5 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-changelog -p conventionalcommits -i OLD_CHANGELOG.md -s -r 1 > CHANGELOG.md

          # 기존 CHANGELOG 내용이 있으면 새로운 내용에 덧붙이기
          if [ -f OLD_CHANGELOG.md ]; then
            cat OLD_CHANGELOG.md >> CHANGELOG.md
            rm OLD_CHANGELOG.md
          fi

          # CHANGELOG.md 파일을 루트 경로로 이동
          mv CHANGELOG.md ../

      - name: Commit & push to PR branch
        run: |
          if git diff --quiet -- CHANGELOG.md frontend/package.json; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add CHANGELOG.md frontend/package.json

          if git diff --cached --quiet; then
            echo "No staged changes."
            exit 0
          fi

          git commit -m "chore(release): prepare for v${{ steps.update_files.outputs.version }}"
          git push origin HEAD:${{ github.head_ref }}
