name: Prepare Release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  prepare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 1. frontend 폴더에서 버전 결정 및 CHANGELOG.md 업데이트
      - name: Update version and CHANGELOG
        id: update_files
        run: |
          cd frontend

          # 다음 버전을 결정하고 package.json에 반영
          BUMP=$(npx -y \
            -p conventional-recommended-bump@9 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-recommended-bump -p conventionalcommits)

          if [ -z "$BUMP" ]; then BUMP=patch; fi

          npm version "$BUMP" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # frontend 폴더에 CHANGELOG.md 생성/업데이트
          npx -y \
            -p conventional-changelog-cli@5 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 1
            
          # CHANGELOG.md 파일을 루트 경로로 이동
          mv CHANGELOG.md ../

      # 2. 루트 경로에서 변경사항 커밋 및 푸시
      - name: Commit & push to PR branch
        run: |
          # 루트에서 변경된 CHANGELOG.md와 frontend의 package.json을 함께 확인
          if git diff --quiet -- CHANGELOG.md frontend/package.json; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add CHANGELOG.md frontend/package.json

          if git diff --cached --quiet; then
            echo "No staged changes."
            exit 0
          fi

          git commit -m "chore(release): prepare for v${{ steps.update_files.outputs.version }}"
          git push origin HEAD:${{ github.head_ref }}
