name: Prepare Release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  prepare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Update version, lockfile, and CHANGELOG
        id: update_files
        run: |
          cd frontend

          BUMP=$(npx -y \
            -p conventional-recommended-bump@9 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-recommended-bump -p conventionalcommits)

          if [ -z "$BUMP" ]; then BUMP=patch; fi

          pnpm version "$BUMP" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          pnpm install --lockfile-only

          # 최신 CHANGELOG 내용을 임시 파일에 생성 (루트 경로에 위치)
          npx -y \
            -p conventional-changelog-cli@5 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-changelog -p conventionalcommits -i OLD_CHANGELOG.md -s -r 1 > ../NEW_CHANGELOG.md
            
          # 기존 CHANGELOG.md 파일이 있다면, 새 내용과 합쳐서 업데이트
          if [ -f ../CHANGELOG.md ]; then
            cat ../NEW_CHANGELOG.md ../CHANGELOG.md > ../TEMP_CHANGELOG.md
            mv ../TEMP_CHANGELOG.md ../CHANGELOG.md
            rm ../NEW_CHANGELOG.md
          else
            mv ../NEW_CHANGELOG.md ../CHANGELOG.md
          fi

          # CHANGELOG.md 파일을 frontend 폴더로 이동했으므로, 다시 루트로 옮길 필요 없음.

      - name: Commit & push to PR branch
        run: |
          # frontend 폴더에서 작업했으므로, 다시 루트로 돌아와서 커밋
          if git diff --quiet -- CHANGELOG.md frontend/package.json frontend/pnpm-lock.yaml; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add CHANGELOG.md frontend/package.json frontend/pnpm-lock.yaml

          if git diff --cached --quiet; then
            echo "No staged changes."
            exit 0
          fi

          git commit -m "chore(release): prepare for v${{ steps.update_files.outputs.version }}"
          git push origin HEAD:${{ github.head_ref }}
