name: Prepare Release

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  prepare:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # 1. frontend 폴더에서 버전 결정 및 package.json 업데이트
      - name: Determine next version (auto)
        id: bump
        run: |
          cd frontend
          BUMP=$(npx -y \
            -p conventional-recommended-bump@9 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-recommended-bump -p conventionalcommits)

          if [ -z "$BUMP" ]; then BUMP=patch; fi

          npm version "$BUMP" --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")

          echo "bump=$BUMP" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 2. 루트 경로에서 CHANGELOG.md 업데이트
      - name: Update CHANGELOG (only latest section)
        run: |
          # --package 옵션으로 frontend의 package.json을 참조하여 루트에 CHANGELOG.md 생성
          npx -y \
            -p conventional-changelog-cli@5 \
            -p conventional-changelog-conventionalcommits@7 \
            conventional-changelog -p conventionalcommits -i CHANGELOG.md -s -r 1 \
            --package frontend/package.json

      # 3. 루트 경로에서 변경사항 커밋 및 푸시
      - name: Commit & push to PR branch
        run: |
          # 변경이 있는지 frontend/package.json, 루트의 CHANGELOG.md를 함께 확인
          if git diff --quiet -- frontend/package.json CHANGELOG.md; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add frontend/package.json CHANGELOG.md

          if git diff --cached --quiet; then
            echo "No staged changes."
            exit 0
          fi

          git commit -m "chore(release): prepare for v${{ steps.bump.outputs.version }}"
          git push origin HEAD:${{ github.head_ref }}
